export const MainConfig = {
  main_data:
    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut    architecto ullam quam porro magnam error.Lorem ipsum dolor, sit amet   consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut architecto ullam quam porro  magnam error.Lorem ipsum dolor, sit amet consectetur adipisicing elit.  Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae  nesciunt, aut architecto ullam quam porro magnam error.Lorem ipsum dolor sit amet consectetur adipisicing elit. Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut    architecto ullam quam porro magnam error.Lorem ipsum dolor, sit amet   consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut architecto ullam quam porro  magnam error.Lorem ipsum dolor, sit amet consectetur adipisicing elit.  Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae  nesciunt, aut architecto ullam quam porro magnam error.Lorem ipsum dolor sit amet consectetur adipisicing elit.'
}

export const CommentConfig = {
  USERNAME:
    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut    architecto ullam quam porro magnam error.Lorem ipsum dolor, sit amet   consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut architecto ullam quam porro  magnam error.Lorem ipsum dolor, sit amet consectetur adipisicing elit.  Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae  nesciunt, aut architecto ullam quam porro magnam error.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
  USERNAME2:
    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut    architecto ullam quam porro magnam error.Lorem ipsum dolor, sit amet   consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut architecto ullam quam porro  magnam error.Lorem ipsum dolor, sit amet consectetur adipisicing elit.  Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae  nesciunt, aut architecto ullam quam porro magnam error.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
  USERNAME3:
    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut    architecto ullam quam porro magnam error.Lorem ipsum dolor, sit amet   consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut architecto ullam quam porro  magnam error.Lorem ipsum dolor, sit amet consectetur adipisicing elit.  Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae  nesciunt, aut architecto ullam quam porro magnam error.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
  USERNAME4:
    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut    architecto ullam quam porro magnam error.Lorem ipsum dolor, sit amet   consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut architecto ullam quam porro  magnam error.Lorem ipsum dolor, sit amet consectetur adipisicing elit.  Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae  nesciunt, aut architecto ullam quam porro magnam error.Lorem ipsum dolor sit amet consectetur adipisicing elit.',
  USERNAME5:
    'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut    architecto ullam quam porro magnam error.Lorem ipsum dolor, sit amet   consectetur adipisicing elit. Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae nesciunt, aut architecto ullam quam porro  magnam error.Lorem ipsum dolor, sit amet consectetur adipisicing elit.  Exercitationem dolorum veritatis voluptate repudiandae, tempora, beatae  nesciunt, aut architecto ullam quam porro magnam error.Lorem ipsum dolor sit amet consectetur adipisicing elit.'
}
